name: StockMarketExercise build & test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v4
      with:
        auto-update-conda: true
  
    - name: Install dependencies and run tests
      run: |
        conda env create --file environment.yml
        conda activate jpm
        pytest tests
  
