name: StockMarketExercise

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: jpm
        environment-file: environment.yml
        python-version: 3.8
        auto-activate-base: false

    - name: Run tests
      run: |
        pytest tests
