name: StockMarketExercise build & test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true

    - name: Create conda environment
      run: conda env create --file environment.yml

    - name: Activate conda environment
      run: conda activate jpm

    - name: Run tests
      run: pytest tests
